-- Migration 043: Career Analyses Table
-- Purpose: Store comprehensive career analysis results from Recipe 1122
-- Dependencies: profiles, workflow_runs, skills_extracted
-- Date: 2025-11-04

BEGIN;

-- Table: career_analyses
-- Stores multi-model career analysis results (organizational, technical, soft skills)
CREATE TABLE career_analyses (
    analysis_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    profile_id INTEGER NOT NULL REFERENCES profiles(profile_id) ON DELETE CASCADE,
    workflow_run_id INTEGER REFERENCES workflow_runs(workflow_run_id) ON DELETE SET NULL,
    
    -- Analysis metadata
    analysis_type TEXT NOT NULL CHECK (analysis_type IN ('full_career', 'period', 'organizational', 'technical', 'soft_skills')),
    period_start TEXT,  -- e.g., "2020", "2020-01", for chunked analysis
    period_end TEXT,    -- e.g., "2025", "2025-11"
    organization TEXT,  -- e.g., "Deutsche Bank", "Novartis"
    role_title TEXT,    -- e.g., "Project Lead Contract Compliance"
    
    -- Analysis results (JSONB for queryability)
    stakeholder_levels JSONB,      -- {"c_level": [...], "directors": [...], "managers": [...]}
    functions_involved JSONB,       -- {"legal": {"why": "...", "activities": [...]}, ...}
    organizational_skills JSONB,    -- {"stakeholder_management": "...", "negotiation": "..."}
    technical_skills JSONB,         -- {"tools": [...], "competencies": [...], "standards": [...]}
    soft_skills JSONB,              -- {"communication": [...], "leadership": [...]}
    career_insights JSONB,          -- {"leadership_level": "...", "scope": "...", "strategic_vs_tactical": "..."}
    
    -- Full markdown report
    analysis_markdown TEXT,
    
    -- Model attribution
    model_used TEXT,  -- e.g., "deepseek-r1:8b", "qwen2.5:7b", "olmo2:7b", "ensemble"
    
    -- Timestamps
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Add index for common queries
CREATE INDEX idx_career_analyses_profile ON career_analyses(profile_id);
CREATE INDEX idx_career_analyses_workflow_run ON career_analyses(workflow_run_id);
CREATE INDEX idx_career_analyses_type ON career_analyses(analysis_type);
CREATE INDEX idx_career_analyses_organization ON career_analyses(organization) WHERE organization IS NOT NULL;

-- Add JSONB GIN indexes for efficient querying
CREATE INDEX idx_career_analyses_stakeholder_levels ON career_analyses USING GIN (stakeholder_levels);
CREATE INDEX idx_career_analyses_functions ON career_analyses USING GIN (functions_involved);
CREATE INDEX idx_career_analyses_org_skills ON career_analyses USING GIN (organizational_skills);
CREATE INDEX idx_career_analyses_tech_skills ON career_analyses USING GIN (technical_skills);
CREATE INDEX idx_career_analyses_soft_skills ON career_analyses USING GIN (soft_skills);

-- Note: Linking to profile_skills is optional - done at application level when needed
-- career_analyses.profile_id can be used to join with profile_skills.profile_id

-- Add trigger for updated_at
CREATE OR REPLACE FUNCTION update_career_analyses_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_career_analyses_updated_at
    BEFORE UPDATE ON career_analyses
    FOR EACH ROW
    EXECUTE FUNCTION update_career_analyses_updated_at();

-- Add comment documentation
COMMENT ON TABLE career_analyses IS 'Stores comprehensive career analysis results from Recipe 1122 multi-model ensemble';
COMMENT ON COLUMN career_analyses.analysis_type IS 'Type of analysis: full_career (entire history), period (time chunk), organizational/technical/soft_skills (model-specific)';
COMMENT ON COLUMN career_analyses.stakeholder_levels IS 'JSONB: C-level, Directors/VPs, Managers, End Users identified in career period';
COMMENT ON COLUMN career_analyses.functions_involved IS 'JSONB: Legal, Procurement, IT, Finance, Compliance, Operations with WHY and activities';
COMMENT ON COLUMN career_analyses.organizational_skills IS 'JSONB: Stakeholder management, negotiation, influence, change management, political savvy';
COMMENT ON COLUMN career_analyses.technical_skills IS 'JSONB: Tools, software, technical competencies, standards, methodologies';
COMMENT ON COLUMN career_analyses.soft_skills IS 'JSONB: Communication, interpersonal, leadership, analytical, personal attributes';
COMMENT ON COLUMN career_analyses.career_insights IS 'JSONB: Leadership level, scope of influence, strategic vs tactical work';
COMMENT ON COLUMN career_analyses.analysis_markdown IS 'Full markdown report generated by synthesis instruction';

COMMIT;

-- Log migration
INSERT INTO migration_log (
    migration_number, 
    migration_name, 
    migration_file,
    applied_at,
    notes
) VALUES (
    '043',
    'career_analyses_table',
    '043_career_analyses_table.sql',
    NOW(),
    'Creates career_analyses table for storing multi-model career analysis results. Links to profiles and workflow_runs. Supports skill matching via profile_id.'
);
