# Gemma3 1B Model Configuration
# Optimized settings for job extraction tasks

# Model Identity
model:
  name: "gemma3:1b"
  provider: "ollama"
  type: "instruction_following"
  
# Generation Parameters
generation:
  temperature: 0.1  # Low for consistent extraction
  max_tokens: 2000
  top_p: 0.9
  top_k: 40
  
# Model-Specific Settings
ollama:
  stream: false
  format: "json"  # Prefer structured output when possible
  
# Performance Tuning
performance:
  expected_response_time: 15  # seconds
  retry_attempts: 2
  batch_size: 1
  
# Quality Expectations
quality:
  min_skills_per_job: 3
  max_skills_per_category: 15
  description_min_length: 50
  description_max_length: 500
