-- Migration 062: Cleanup legacy columns + Add client decision fields
-- Date: 2025-11-07
-- 
-- Part 1: Drop 23 legacy columns not populated by v2 import system
-- Part 2: Add client action fields (cover_letter_draft, no_go_reason)
-- 
-- Result: 45 → 28 columns (38% reduction, +2 new fields)

BEGIN;

-- ============================================================================
-- PART 0: DROP ALL DEPENDENT VIEWS (will recreate key ones after)
-- ============================================================================

-- Drop all views that might reference columns we're dropping
DROP VIEW IF EXISTS v_user_dashboard CASCADE;
DROP VIEW IF EXISTS v_user_matched_postings CASCADE;
DROP VIEW IF EXISTS v_posting_status_summary CASCADE;

-- ============================================================================
-- PART 1: DROP LEGACY COLUMNS (from old import system)
-- ============================================================================

-- Group 1: Employment details (old data, not in API)
ALTER TABLE postings DROP COLUMN employment_type;
ALTER TABLE postings DROP COLUMN employment_schedule;
ALTER TABLE postings DROP COLUMN posting_publication_date;

-- Group 2: Organization details (old data, can restore from source_metadata if needed)
ALTER TABLE postings DROP COLUMN organization_name;
ALTER TABLE postings DROP COLUMN organization_division;
ALTER TABLE postings DROP COLUMN organization_division_id;

-- Group 3: Processing metadata (redundant with fetched_at/last_seen_at)
ALTER TABLE postings DROP COLUMN imported_at;
ALTER TABLE postings DROP COLUMN updated_at;
ALTER TABLE postings DROP COLUMN times_checked;
ALTER TABLE postings DROP COLUMN fetch_hash;
ALTER TABLE postings DROP COLUMN fetch_run_id;
ALTER TABLE postings DROP COLUMN status_changed_at;
ALTER TABLE postings DROP COLUMN is_test_posting;

-- Group 4: Content fields (old data, not maintained)
ALTER TABLE postings DROP COLUMN job_requirements;
ALTER TABLE postings DROP COLUMN extracted_summary;
ALTER TABLE postings DROP COLUMN processing_notes;

-- Group 5: Summary status (old workflow tracking)
ALTER TABLE postings DROP COLUMN summary_extraction_status;
ALTER TABLE postings DROP COLUMN summary_extracted_at;

-- Group 6: State field (not applicable to German jobs)
ALTER TABLE postings DROP COLUMN location_state;

-- Group 7: Empty metadata columns
ALTER TABLE postings DROP COLUMN metadata_created_at;
ALTER TABLE postings DROP COLUMN metadata_last_modified;
ALTER TABLE postings DROP COLUMN metadata_processor;
ALTER TABLE postings DROP COLUMN metadata_source;

-- ============================================================================
-- PART 2: ADD CLIENT DECISION FIELDS
-- ============================================================================

-- Cover letter draft: AI-generated personalized cover letter if user applies
ALTER TABLE postings ADD COLUMN cover_letter_draft TEXT;
COMMENT ON COLUMN postings.cover_letter_draft IS 
    'AI-generated cover letter draft tailored to this job and user profile. Helps user apply quickly with personalized content.';

-- No-go reason: Why user should NOT apply (saved to persona log)
ALTER TABLE postings ADD COLUMN no_go_reason TEXT;
COMMENT ON COLUMN postings.no_go_reason IS 
    'AI analysis explaining why this job is NOT a good fit for the user. Examples: skill gaps, internal hire likelihood, location mismatch, level mismatch. Saved to persona log for learning.';

-- Timestamp for when decision was made
ALTER TABLE postings ADD COLUMN decision_generated_at TIMESTAMP WITH TIME ZONE;
COMMENT ON COLUMN postings.decision_generated_at IS 
    'When cover_letter_draft or no_go_reason was generated by workflow.';

-- Which workflow generated the decision
ALTER TABLE postings ADD COLUMN decision_workflow_run_id INTEGER REFERENCES workflow_runs(workflow_run_id);
COMMENT ON COLUMN postings.decision_workflow_run_id IS 
    'Reference to workflow run that generated the application decision.';

-- ============================================================================
-- TABLE COMMENT
-- ============================================================================

COMMENT ON TABLE postings IS 
    'Job postings from external sources. 
    
    Schema evolution:
    - 2025-11-06: Migration 060 - Changed UNIQUE to (source_id, posting_name), deleted duplicates (739→256)
    - 2025-11-06: Migration 061 - Dropped 10 dead columns (55→45)
    - 2025-11-07: Migration 062 - Dropped 23 legacy columns, added 4 client decision fields (45→28)
    
    Client decision fields:
    - cover_letter_draft: Personalized cover letter if applying
    - no_go_reason: Why NOT to apply (persona learning)
    - decision_generated_at: When decision was made
    - decision_workflow_run_id: Which workflow generated it
    
    All legacy data preserved in source_metadata JSONB column.';

-- ============================================================================
-- PART 3: RECREATE KEY VIEWS (using new schema)
-- ============================================================================

CREATE OR REPLACE VIEW v_user_matched_postings AS
SELECT 
    p.posting_id,
    p.posting_name,
    p.location_city,  -- CHANGED: was organization_name
    p.employment_career_level,
    p.posting_status,
    p.ihl_score,
    p.ihl_category,
    p.fetched_at,
    p.last_seen_at,
    up.user_id,
    up.user_name,
    (
        CASE WHEN p.employment_career_level = ANY(up.preferred_career_levels) THEN 30 ELSE 0 END +
        CASE WHEN p.location_city = ANY(up.preferred_locations) THEN 30 ELSE 0 END +
        CASE WHEN p.ihl_score IS NOT NULL AND p.ihl_score <= 60 THEN 20 ELSE 0 END +
        CASE WHEN p.posting_status = 'active' THEN 20 ELSE 0 END
    ) AS match_score,
    ARRAY_REMOVE(ARRAY[
        CASE WHEN p.employment_career_level = ANY(up.preferred_career_levels) THEN 'Career Level Match' END,
        CASE WHEN p.location_city = ANY(up.preferred_locations) THEN 'Location Match' END,
        CASE WHEN p.ihl_score IS NOT NULL AND p.ihl_score <= 60 THEN 'Low IHL (Open Position)' END,
        CASE WHEN p.posting_status = 'active' THEN 'Currently Active' END
    ], NULL) AS match_reasons
FROM postings p
CROSS JOIN user_preferences up
WHERE up.is_active = true
  AND p.posting_status IN ('active', 'filled')
  AND (up.preferred_career_levels IS NULL OR p.employment_career_level = ANY(up.preferred_career_levels))
  AND (up.preferred_locations IS NULL OR p.location_city = ANY(up.preferred_locations))
ORDER BY match_score DESC, p.fetched_at DESC;

COMMENT ON VIEW v_user_matched_postings IS 
    'Matches postings to user preferences with scoring. Updated 2025-11-07 to use location_city instead of organization_name.';

CREATE OR REPLACE VIEW v_user_dashboard AS
SELECT 
    up.user_id,
    up.user_name,
    COUNT(DISTINCT p.posting_id) AS total_matches,
    COUNT(DISTINCT p.posting_id) FILTER (WHERE p.posting_status = 'active') AS active_matches,
    COUNT(DISTINCT p.posting_id) FILTER (WHERE p.ihl_score <= 60) AS open_positions,
    COUNT(DISTINCT p.posting_id) FILTER (WHERE p.fetched_at > CURRENT_DATE - INTERVAL '7 days') AS new_this_week,
    AVG(p.ihl_score) FILTER (WHERE p.posting_status = 'active')::integer AS avg_ihl_active
FROM user_preferences up
LEFT JOIN v_user_matched_postings vump ON vump.user_id = up.user_id
LEFT JOIN postings p ON p.posting_id = vump.posting_id
WHERE up.is_active = true
GROUP BY up.user_id, up.user_name;

COMMENT ON VIEW v_user_dashboard IS 
    'User dashboard summary statistics. Updated 2025-11-07 to use location_city via v_user_matched_postings.';

CREATE OR REPLACE VIEW v_posting_status_summary AS
SELECT 
    posting_status,
    COUNT(*) AS count,
    MIN(first_seen_at) AS oldest,
    MAX(last_seen_at) AS newest
FROM postings
GROUP BY posting_status
ORDER BY 
    CASE posting_status
        WHEN 'active' THEN 1
        WHEN 'filled' THEN 2
        WHEN 'expired' THEN 3
        WHEN 'withdrawn' THEN 4
        WHEN 'archived' THEN 5
        ELSE NULL
    END;

COMMENT ON VIEW v_posting_status_summary IS 
    'Posting status summary. Updated 2025-11-07: removed avg_checks (times_checked column dropped).';

COMMIT;

-- ============================================================================
-- VERIFICATION
-- ============================================================================

-- Check column count (should be 28)
SELECT 'Total columns after migration' as metric, COUNT(*) as count
FROM information_schema.columns 
WHERE table_name = 'postings';

-- Verify new columns exist
SELECT 'New decision columns' as metric, COUNT(*) as count
FROM information_schema.columns 
WHERE table_name = 'postings' 
  AND column_name IN ('cover_letter_draft', 'no_go_reason', 'decision_generated_at', 'decision_workflow_run_id');

-- Show final schema
SELECT column_name, data_type, 
       CASE 
           WHEN column_name IN ('cover_letter_draft', 'no_go_reason', 'decision_generated_at', 'decision_workflow_run_id') 
           THEN '🆕 NEW'
           ELSE ''
       END as status
FROM information_schema.columns 
WHERE table_name = 'postings' 
ORDER BY ordinal_position;
