specialist_info:
  name: "relationship_compatibility"
  version: "1.0"
  description: "Emotional and romantic compatibility assessment with culturally-aware analysis"
  author: "Ada & Arden - Consciousness Collaboration"
  category: "critical"
  tags: ["relationships", "compatibility", "emotional_intelligence", "love", "cultural_awareness"]

# Performance requirements
performance:
  max_response_time: 30  # seconds
  max_memory_usage: 100  # MB
  target_success_rate: 0.95
  concurrent_requests: 3

# Model configuration for LLM integration
model_config:
  default_model: "llama3.2:latest"
  temperature: 0.2  # Slightly higher for emotional nuance
  max_tokens: 4000
  timeout: 30

# Relationship compatibility scoring configuration
compatibility_config:
  emotional_dimensions:
    - processing_styles
    - expression_patterns
    - regulation_strategies
    - intelligence_empathy
    - core_needs
    - trigger_patterns
    - cultural_context
    - growth_compatibility
    - safety_creation
  
  scoring_weights:
    emotional_harmony: 0.25
    communication_compatibility: 0.20
    growth_alignment: 0.15
    cultural_sensitivity: 0.15
    safety_creation: 0.15
    trigger_management: 0.10
  
  compatibility_ranges:
    excellent: 85-100
    very_good: 70-84
    good: 55-69
    fair: 40-54
    needs_work: 20-39
    concerning: 0-19
  
  safety_thresholds:
    require_professional_help: 20
    flag_concerning_patterns: 30
    recommend_counseling: 50

# Cultural considerations
cultural_config:
  expression_styles:
    - individualistic_vs_collectivistic
    - direct_vs_indirect_communication
    - emotional_openness_norms
    - family_involvement_expectations
    - conflict_resolution_traditions
  
  safety_considerations:
    - power_dynamics_awareness
    - consent_culture_understanding
    - emotional_manipulation_detection
    - healthy_boundary_respect

# Output format
output_format:
  include_cultural_analysis: true
  include_safety_assessment: true
  include_growth_opportunities: true
  include_practical_guidance: true
  conservative_bias: true  # Err on side of caution for relationships
